services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: university_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
